services:
  flask_dw_lacrei:
    build: .
    container_name: flask_dw_lacrei
    ports:
      - "5006:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: python run.py

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_lacrei_bi
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      # Idioma opcional
      MB_SITE_LOCALE: pt
    volumes:
      - metabase_data:/metabase-data
    restart: always

volumes:
  metabase_data:
